### ISSUE TITLE
No <>| on german layout

### ISSUE THREAD

**Issue by martin-mmmm** [blahlicus/arbites-family#18]
Hello,
there is a key on the german keyboard-layout qwertz which is left from Y, but it seems that it is missing in the software.
Is there another way to add these keys?
 \> < |

Thank you!

**Comment by martin-mmmm** [comment]
The keys are available on the us-layout, so it should be possible to use them in the german layout, if it is implemented correctly.

**Comment by blahlicus** [comment]
Hey, that key (<>|) is actually already in Arbites, the display text for that scancode is not correctly modified in the German layout setting so it is not currently displaying correctly in Arbites.

Use the \| key in the key menu in Arbites with Deutsche T1, it will output the <>| keys correctly instead of the displayed \| keys.
![image](https://imgur.com/uXrbOHV)
I'm currently on vacation so I'll have the display text fixed once I get back, but for now just use the \| key which is really the <>| key but incorrectly displayed.

**Comment by martin-mmmm** [comment]
Hey, thank you soo much!
works now like it should.
