### ISSUE TITLE
Buttons with Null values to have a different color

### ISSUE THREAD

**Issue by accidentalrebel** [blahlicus/arbites-family#2]
This is not an issue but more of a feature suggestion. 

I think it would really help if buttons with a "Null" value is of a different color as the other buttons. This can help users see at a glance which of the buttons are not yet set.

Here is how it would look like: 
![null_buttons](https://cloud.githubusercontent.com/assets/1009214/15507205/2d78e64e-21fd-11e6-819b-7c703fab4743.PNG)

@blahlicus, I've pulled the repo and made the change on my end. I can do also do a pull request if it is okay with you.

Thanks!

**Comment by blahlicus** [comment]
Hey, you didn't sync your repo so I can't see the code change, I would love to be able to do this, but keeping the code cross-platform capable makes styling very difficult without having it mess up something for a specific platform.

**Comment by accidentalrebel** [comment]
I actually have not pushed my changes yet. Will do so in a bit, just wrestling with some git stuff first. Will let you know. Thanks!

**Comment by blahlicus** [comment]
Thanks! Keep me posted, working with Eto.Forms could be fun but at the same time challenging because of the lack of some in-depth documentation.

**Comment by accidentalrebel** [comment]
Ah, I see what you mean when about styling difficulties across platforms.

I actually only did the following:

```
if (kd.key.val == 0)
    btn.BackgroundColor = new Color(0.8f, 0.8f, 0.8f);
else
    btn.BackgroundColor = new Color();
```

After reading your comment I realized that the approach should be different because it uses Eto. 

I see that the button changes to a blue color when your mouse is over it but can't find the actual code that does this. Can you point me in the right direction? I am very curious and eager to make this work properly. :)

**Comment by blahlicus** [comment]
Hey, Eto.Forms does support [platform specific styling](https://github.com/picoe/Eto/wiki/Styling) (the platforms being winforms/wpf/Gtk2/Gtk3/Cocoa), so you could style them with platform specific native code.

The button is blue when the mouse is over it in your case because you are running arbites under Gtk2/3 (I'm guessing via windows/mono), and the gtk.css style for `selected_bg_color` was set to blue, I believe you could write platform specific style to a specific button by doing the following.

Insert the following code at the beginning of the application (Program.cs would work) and check for platform.
```
Eto.Style.Add<Button>("null-button", btn=> {
    // insert platform specific styling code here
})
```
Insert this part in `void LoadLayout()` of UCLayer.cs when refreshing the buttons
```
foreach (Button btn in buttons)
{
  if (btn.Text == "Null")
  {
    btn.Style = "null-button";
  }
}
````

Regardless, doing such styling work would require you to write platform specific code for all the platforms (aforementioned winforms/gtk/etc) and to have good enough knowledge on those platforms, so its definitely a lot more work that what you might be willing to put in.

_____

The older winforms based Arbites was actually really beautiful:

![screenshot](http://i.imgur.com/uHyQwve.png)

Because it was platform specific, styling was really easy, but I don't have the knowledge necessary to work with the various platforms and Eto.Forms' current state of development is not necessarily mature, so compromises have to be made.

**Comment by accidentalrebel** [comment]
I think the link about [platform specific styling](https://github.com/picoe/Eto/wiki/Styling) should only be done only when there is a need for one platform to have a different styling from others (For example, Windows buttons would be color red while Mac would be color white). Otherwise, in our case since we wan't the color to be consistent on all platforms then the code I've listed should. in theory, work.

I however not tested this yet as my environment is currently not set up properly to be able to test on a Mac and Linux, so if you are able to test it on your end then that would be great. [Here is my push](https://github.com/accidentalrebel/arbites-family/commit/ec3d5603ccdc157f4ddc4b7dd7969b9d507d32ad).

If you already know that this won't work then feel free to disregard this change for now.

Thanks!

**Comment by blahlicus** [comment]
Implemented and added colour highlights via the use of systemcolors, it doesn't work in mac and linux and only works under wpf or winforms

**Comment by blahlicus** [comment]
see [commit](https://github.com/blahlicus/arbites-family/tree/152249a9b522f2a410f3d34e4d8334ff445e284e)

**Comment by accidentalrebel** [comment]
Confirmed working on Windows. Thanks!
