### ISSUE TITLE
Failed to upload

### ISSUE THREAD

**Issue by paldepind** [blahlicus/arbites-family#9]
I just received my Diverge TM 2. But I am having problems with updating the layout. I am using Linux. The screenshots below show the error I'm experiencing.

![image](https://user-images.githubusercontent.com/521604/28114563-9947f7da-6701-11e7-8a15-1567ed6a61f3.png)

Note that the port I can select in the screenshort above only appeas when my TM 2 is actually connected. So it appears that Arbites correctly detects the keyboard. But something apparently still doesn't work.

![image](https://user-images.githubusercontent.com/521604/28114587-b519eb76-6701-11e7-851d-44594300add0.png)

When I click "Yes" above I see this.

![image](https://user-images.githubusercontent.com/521604/28114756-7878aab2-6702-11e7-96ee-d5ad68678f88.png)

I am using Arch Linux and I've installed Mono and the GTK bindings like this

```
pacman -S mono gtk-sharp-2
```

**Comment by blahlicus** [comment]
Hey, I see, if Arbites was able to detect the board but not upload to the board, then it could be a permissions issue, either add your user to the `dialout` usergroup (recommended), or run Arbites with elevated privileges. Do let me know how it goes.

**Comment by paldepind** [comment]
Thank you for the answer @blahlicus. I apologize for my slow response.

I've tried running Arbites as root with `sudo mono ArbitesEto2.Gtk2.exe` but it doesn't make a difference. I get the same error.

**Comment by blahlicus** [comment]
Hey, it seems that arch's case is slightly different from Debian and RedHat, root by default does not have serial port write access as well, according to [this forum post](https://bbs.archlinux.org/viewtopic.php?pid=1368487#p1368487), instead of needing to be part of the `dialout` usergroup, you need to add the `lock` usergroup to your user and install the linked Arduino package and lock patch, please do try out that solution from that post and see if it works on Arch.
